### ISSUE TITLE
logo is bigg oof

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GregTech-Intergalactical/GregTech#1]
it is oof

**Comment by PoptartOverlord-Xabedo** [comment]
i suggest this as the new logo

![positivethoughts](https://user-images.githubusercontent.com/40670872/73114479-9554f680-3f23-11ea-850e-9ef6a6a9298a.png)

**Comment by Muramasa-** [comment]
Feel free to send me a better one, I'm not an artist

**Comment by GregoriusT** [comment]
I think the Hand Part of that Smiley is already used in some GregTech Port. Also I think the G Logo is cute. XD
