### ISSUE TITLE
Recipe compat with Create & Immersive Engineering

### ISSUE THREAD

**Issue by KaktuszSok** [GregTech-Intergalactical/GregTech#101]
It would make sense for ULV (and perhaps LV) tier recipes to be compatible with create and IE machines. This could be disabled through a config option, preferably by making the max voltage adjustable and -1 indicating disabled.

Create:
Pulverising w/ crushing wheels
Ore washing w/ fans
Making plates w/ mechanical press
Mixing w/ mechanical mixer

IE:
Pulversing w/ crusher
Mixing w/ mixer

I may be forgetting some.

**Comment by Rongmario** [comment]
Compatibility will likely come from an addon.

**Comment by Vliro** [comment]
Or not even an add-on, a datapack would suffice for this.

**Comment by Trinsdar** [comment]
Closing this as I have no plans to do recipes in those machines, however it can easily be done via a data pack or something if someone wants that
