### ISSUE TITLE
Recipes datapack support

### ISSUE THREAD

**Issue by rlqd** [GregTech-Intergalactical/GregTech#103]
It would be extremely useful for modpack makers to add their own recipes to GT machines.
Currently it fails to load a datapack with this recipe for example:
`{
	"type":"antimatter:gt.recipe_map.pulverizing",
	"group":"waystones",
	"ingredient":{
		"item":"waystones:warp_stone"
	},
	"result":"waystones:warp_dust"
}`

> Failed to parse recipe 'minecraft:test[antimatter:gt.recipe_map.pulverizing]'! Falling back to vanilla: java.lang.NullPointerException: Unknown recipe type: antimatter:gt.recipe_map.pulverizing

Datapack recipes are vanilla thing, so looks like an easy yet useful feature to implement.
And as a bonus, kubejs has datapack recipes support.

P.S. Full kubejs integration will be useful too though, however it looks more complex to implement.

**Comment by Vliro** [comment]
Datapacks and kubeJS are supported. See the discord for example. The type is always antimatter:machine, but you have to specify the map.

{
  "type": "antimatter:machine",
  "item_in": [
    {
      "tag": "forge:ores/iron",
      "count": 1
    }
  ],
  "item_out": [
    {
      "item": "minecraft:iron_ingot",
      "count": 2
    }
  ],
  "euT": 8,
  "duration": 80,
  "map": "gti:chemical_reacting"
}


You can now add json recipes!

**Comment by Rongmario** [comment]
Will close this and start working on a wiki page somewhere, maybe within the github repo.
