### ISSUE TITLE
[1.16.5] Adding this mod and the two api mods causes perm damage to world - Payload may not be larger than

### ISSUE THREAD

**Issue by ProsperCraft** [GregTech-Intergalactical/GregTech#118]
![image](https://user-images.githubusercontent.com/4427684/146519771-947cdae2-532b-44de-a154-3a4590f47c1a.png)

It took me a long time to figure this one out, but after adding this mod to my TownCraft TWO modpack we were no longer able to log in to a dedicated server, I rolled back the pack prior to the update but the world still would not allow us to log in, resetting the world with the pack prior to the update that added Gregtech we were able to log in, adding this mod made it happen again.

Modpack- [TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft)

[Gregtech Dedicated server log.zip](https://github.com/GregTech-Intergalactical/GregTech/files/7733938/Gregtech.Dedicated.server.log.zip)

Server latest.log - https://gist.github.com/ProsperCraft/78ed68f6cb0d402bb93d09a087eb3af1

Client latest.log - https://gist.github.com/ProsperCraft/72c38018f2031f782515d7f8eb27f9a4

Client debug.log - https://gist.github.com/ProsperCraft/582048b518eb538c985dfaab2ee5a693

**Comment by Vliro** [comment]
What forge version are you on? Do you have many recipes in the pack?

**Comment by Vliro** [comment]
I might add that GTI has moved stable version to 1.18 but if there is an issue here that needs urgent fixing it will be added to 1.16 branch. 

Also, did you download from Curseforge? If so they are very outdated unfortunately and not up to date.

**Comment by ProsperCraft** [comment]
Forge version 36.2.22  pulled from line 147 of the log.

Yes there are 250 mods in the pack, lots of recopies.

Yes, I downloaded from Curseforge- that is how modpacks work these days.  I can't imagine doing it any other way honestly, even if there was a different version available out there, I would not be allowed to distribute it via the launcher if it wasn't on curseforge without a massive amount of manual review and problems getting each update approved.

1.16.5 is the LTS version of Forge, I have not heard of any of my other mod authors dropping it, I guess we will just have to catch you in 1.18 and not include it in 1.16.5 as I had hoped.

**Comment by Vliro** [comment]
Yes I am aware. I would like to support for 1.16 as well but I don't have time. Also GTI is under very heavy development hence why CF is not always up to date.

I'm not exactly sure of the issue but it should be that too many recipes are sent at once which might cause issues. This should be alleviated in later versions. 

The goal is to stabilize now for 1.18 finally and offer proper support.

**Comment by Trinsdar** [comment]
1.16 is no longer supported
