### ISSUE TITLE
[1.18.1] Broken metal plate recipes

### ISSUE THREAD

**Issue by k2aj** [GregTech-Intergalactical/GregTech#119]
Hello,
the early game recipe for crafting metal plates seems to be broken. The current recipe requires two metal plates and a hammer to craft a metal plate, effectively making metal plates uncraftable in the early game. I'm assuming the recipe was supposed to use two ingots instead (like in Gregtech 5).

Minecraft 1.18.1
Forge 39.0.5
jei-1.18.1-9.1.0.44
GregTech Intergalactical 1.18.1-0.1
Antimatter API 1.18.1-0.1
Tesseract API 1.18.1-0.1

Screenshots:
![jei](https://user-images.githubusercontent.com/43889210/146639627-d45fd6bb-71b9-4401-bbfd-270494f12bc1.png)
![actual](https://user-images.githubusercontent.com/43889210/146639416-64eb4433-8969-40ff-bc5c-bf6f5c433ce7.png)
![expected](https://user-images.githubusercontent.com/43889210/146639462-dc6759ff-2056-42a3-92b4-f3f11a12a61a.png)

**Comment by Vliro** [comment]
Fixed already in latest nightly. As you thought it's just a mistake
https://github.com/GregTech-Intergalactical/AntimatterAPI/actions/runs/1595564098
