### ISSUE TITLE
[1.18.2] Please nerf the rubber tree spawn rate, way way way too many trees.

### ISSUE THREAD

**Issue by ProsperCraft** [GregTech-Intergalactical/GregTech#127]
About 20% of what is is currently spawning at would be good.
![2022-06-07_16 03 08](https://user-images.githubusercontent.com/4427684/172490748-99aa02f3-3016-4145-a346-7496bc9c64e5.png)
![2022-06-07_16 03 23](https://user-images.githubusercontent.com/4427684/172490762-ad93b04f-64dd-4325-aa8d-a92b71858a51.png)

**Comment by Trinsdar** [comment]
issue should be fixed in gtrubber now, and gt rubber will be packaged with gregtech on the next release
