### ISSUE TITLE
mod seems to conflixt with another mod

### ISSUE THREAD

**Issue by xXxAVARITIAxXx** [GregTech-Intergalactical/GregTech#132]
when ever i use greg tech 1.18.2 and antimatter together with chunk by chunk, it stops working, and it gives an error on the server log that there is an issue with chunk by chunk, it works fine in single player, but i been trying to make a modpack that is server compatible, and because the pack is based on chunk by chunk mod i could not remove it, and i would like to see both the mods being compatible so that i can use greg tech together with my pack considering how tech reborn is not a thing anymore for fabric, also the pack i made works fine after removing greg tech, it also works fine if i leave greg tech and removes chunk by chunk, and idk if it conflicts because antimatter has its own world gen stuff, if i need an error log to show the problem im glad to give one, just have to add the mod back to the server to make the conflict

**Comment by Trinsdar** [comment]
can't help cause no useful info was provided
