### ISSUE TITLE
[1.18.2][Fabric][Sodium] Machine render not work

### ISSUE THREAD

**Issue by JustInk-Soul** [GregTech-Intergalactical/GregTech#133]
# Minecraft version: 1.18.2 + Fabric 0.14.9

## Sodium
![2022-10-16_16 54 51](https://user-images.githubusercontent.com/90371792/196027145-bb269758-0b3e-4dfc-ba01-edb1d8a9fc33.png)

## Remove Sodium
![2022-10-16_13 56 07](https://user-images.githubusercontent.com/90371792/196027897-75d4b84d-d1bc-423e-a6ab-0edcee678f14.png)

## Modlist:
> TesseractAPI 0.1
> AntimatterAPI 0.1
> GregTech Intergalactical 0.1
> Modern Industrialization 1.2.2
> RoughlyEnoughItems 8.3.549
> Iris Shaders 1.4.0
> Ksyxis 1.1
> Language Reload 1.2.1
> LazyDFU 0.1.2
> Sodium 0.4.1+build.15
> Indium 1.0.7
> Architectury 4.9.84
> Cloth-Config 6.4.90
> Fabric Language Kotlin 1.8.4+kotlin.1.7.20
> Fabric API 0.59.0

## Log
[latest.log](https://github.com/GregTech-Intergalactical/GregTech/files/9794011/latest.log)

**Comment by Trinsdar** [comment]
I am pretty sure i already fixed this issue in dev, except for lighting, lighting still doesn't always work with sodium
