### ISSUE TITLE
(1.16.5) Minecraft launch problem : java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by Koynax** [GregTech-Intergalactical/GregTech#134]
Hello, I have a problem with version 1.16.5. I can't launch my minecraft with the mod. During the launch an error occurs. I have GregTech Intergalactical version 0.0.5, AntimatterAPI 0.1.1 and TesseractAPI 0.1. I have only these 3 mods. Can you help me? I could see that I am not the only one with this problem. I tried with Forge 36.2.33, Forge 36.2.34, Forge 36.2.30, Forge 36.2.39

![Capture](https://user-images.githubusercontent.com/77029482/196760668-86425655-1088-4c1c-ac7a-08937068558a.PNG)

![image](https://user-images.githubusercontent.com/77029482/196763299-f36e0c2b-5dd9-4933-baaf-f099151d3110.png)

**Comment by Trinsdar** [comment]
duplicate

**Comment by Zscreeper** [comment]
where is it duplicated? without these 2 APIs, GregTech itself will not work
