### ISSUE TITLE
Misssing recipes 1.18.2

### ISSUE THREAD

**Issue by Dermix121** [GregTech-Intergalactical/GregTech#135]
Hi there .
I noticed that when the mod with all 2 necessary additional mods (TesseractAPI, AntimatterAPI)
Many blcks, for example, do not have a recipe for the basic building blocks of multi-block machines for higher level machines.

**Comment by lynxx131** [comment]
I've created PR #142 which should hopefully address some missing recipes.

@Dermix121 If you could provide any examples that aren't on my list in the above PR then I can take another look.
