### ISSUE TITLE
Can't get the Sticky Resin using a bronze machine to carry out the Industrial Revolution into the Electric Age

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#147]
无法使用锤子右击橡胶树获得粘性树脂，只能获得生橡胶粉。

You can't right-click Rubber Log with Hammer to get Sticky Resin, you can only get Raw Rubber Dust.
——Translate by Microsoft Bing Translator

**Comment by Trinsdar** [comment]
should be fixed in latest version in github actions, though it's in alpha right now
