### ISSUE TITLE
Recipe formatting in REI seems broken

### ISSUE THREAD

**Issue by lynxx131** [GregTech-Intergalactical/GregTech#148]
When viewing a machine's recipes i.e. all compressing recipes the info screen is not formatted correctly:

https://i.imgur.com/wWH5qKn.png (Fabric)
https://i.imgur.com/aAge8x1.png (Forge)

Looks as if everything just needs pushing up a bit.

**Comment by lynxx131** [comment]
JEI seems to be fine, only seems to be REI but I've only tried in a dev client, I've not tried REI in a real client as I only use JEI on Forge.

**Comment by Trinsdar** [comment]
Yah rei compat isn't completely finished yet

**Comment by Trinsdar** [comment]
this should be fixed now
