### ISSUE TITLE
proxy block crash

### ISSUE THREAD

**Issue by StockiesLad** [GregTech-Intergalactical/GregTech#154]
[B#768]  java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2350.ordinal()" because "this.facing" is null
[B#768]  	at muramasa.antimatter.tile.TileEntityFakeBlock.writeTag(TileEntityFakeBlock.java:162)
[B#768]  	at muramasa.antimatter.tile.TileEntityFakeBlock.method_16887(TileEntityFakeBlock.java:151)
[B#768]  	at net.minecraft.class_2622.method_39026(class_2622.java:21)
[B#768]  	at net.minecraft.class_2622.method_38585(class_2622.java:25)
[B#768]  	at muramasa.antimatter.tile.TileEntityBase.getUpdatePacket(TileEntityBase.java:69)
[B#768]  	at muramasa.antimatter.tile.TileEntityBase.method_38235(TileEntityBase.java:20)
[B#768]  	at net.minecraft.class_3193.method_14009(class_3193.java:300)
[B#768]  	at net.minecraft.class_3193.method_30311(class_3193.java:293)
[B#768]  	at net.minecraft.class_3193.method_14006(class_3193.java:278)
[B#768]  	at net.minecraft.class_3215.method_38784(class_3215.java:389)
[B#768]  	at it.unimi.dsi.fastutil.objects.ObjectLinkedOpenHashSet.forEach(ObjectLinkedOpenHashSet.java:1228)
[B#768]  	at net.minecraft.class_3215.redirect$kio000$flushActiveChunks(class_3215.java:2162)
[B#768]  	at net.minecraft.class_3215.method_14161(class_3215.java:389)
[B#768]  	at net.minecraft.class_3215.method_12127(class_3215.java:322)
[B#768]  	at net.minecraft.class_3218.method_18765(class_3218.java:311)
[B#768]  	at net.minecraft.server.MinecraftServer.redirect$dmo000$fixUpdateSuppressionCrashTick(MinecraftServer.java:8290)
[B#768]  	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
[B#768]  	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
[B#768]  	at net.minecraft.class_1132.method_3748(class_1132.java:97)
[B#768]  	at net.minecraft.server.MinecraftServer.handler$dfk000$modifiedRunLoop(MinecraftServer.java:7396)
[B#768]  	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
[B#768]  	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
[B#768]  	at java.base/java.lang.Thread.run(Thread.java:833)
[B#768]  

you just need to fix the facing direction its really easy

**Comment by Trinsdar** [comment]
fixed

**Comment by StockiesLad** [comment]
👍
