### ISSUE TITLE
1.18.2 Crash. java.lang.NoSuchFieldError: ENERGY_HANDLER_CAPABILITY 1.18.2 forge

### ISSUE THREAD

**Issue by GRKTheGreat** [GregTech-Intergalactical/GregTech#166]
Log : https://paste.ee/p/6JNyT
Latest : https://paste.ee/p/6SjC1
DeBug : https://paste.ee/p/vUQ3R
Mods :AppleSkin (by squeek502)
FTB Library (Forge) (by FTB)
Controlling (by Jaredlll08)
FTB Ultimine (Forge) (by FTB)
Architectury API (Fabric/Forge) (by shedaniel)
Clumps (by Jaredlll08)
JourneyMap (by techbrew)
Mouse Tweaks (by YaLTeR)
GregTech Intergalactical (by tactinic)
AntimatterAPI (by tactic)
TesseractAPI (by taktiic )
Just Enough Items (JEI) (by mezz)

**Comment by Trinsdar** [comment]
Don't update tesseract yet, those old versions of antimatter and gregtech aren't compatible with the new version of tesseract

**Comment by GRKTheGreat** [comment]
> Don't update tesseract yet, those old versions of antimatter and gregtech aren't compatible with the new version of tesseract

it is up to date, 3/1/2023

**Comment by Trinsdar** [comment]
I'm saying not to use that new version of tesseract yet

**Comment by GRKTheGreat** [comment]
> I'm saying not to use that new version of tesseract yet

Thanks! Works
