### ISSUE TITLE
Give us downloadable jar file

### ISSUE THREAD

**Issue by videogamesrcool** [GregTech-Intergalactical/GregTech#183]
### Describe the feature

Literally title. I am no coding genius but I cannot figure out how to download this from github

### Reasons why it should be considered

It is easier than having to code

### Please Read and Confirm the Following

- [X] I have confirmed this feature request is unique and has not been suggested already.

**Comment by stacode123** [comment]
Step 1. Press the actions tab
![Screenshot from 2024-01-01 09-59-23](https://github.com/GregTech-Intergalactical/GregTech/assets/49679054/28f39789-4b40-4529-82b0-cfbf6e44cb3d)
Step 2. press on the **LATEST** entry on the list

![Screenshot from 2024-01-01 10-00-44](https://github.com/GregTech-Intergalactical/GregTech/assets/49679054/98e49f56-098d-413a-beed-e1bbb76b94ea)
Step 3 Download the JAR
![Screenshot from 2024-01-01 10-01-37](https://github.com/GregTech-Intergalactical/GregTech/assets/49679054/1f970011-c9f7-4a9a-843b-2f7c4f486c58)
Remeber that these are in development builds with bugs so dont expect support.
You wanted the JAR you have it
