### ISSUE TITLE
The voltage used in electrolytic alumina is a bit high and the current is too low.

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#192]
### Describe the feature

The current recipe voltage and current uses 32V (AKA: EU/t) 1A, the voltage is a little high, and the current is too low.
In my opinion, using 8V 4A or 8V 8A or even 8V 12A is a more reasonable recipe.
——Translate by Bing Translator

### Reasons why it should be considered

In reality, low-voltage and high-current are usually used for electrolytic aluminum operations.
——Translate by Bing Translator

### Additional details

![image](https://github.com/GregTech-Intergalactical/GregTech/assets/49526021/dab2a2d2-7990-4ed7-aaeb-78f9e2108a9c)

### Please Read and Confirm the Following

- [X] I have confirmed this feature request is unique and has not been suggested already.

**Comment by Trinsdar** [comment]
1. it costs that much on purpose, I am not changing it to cost less
2. changing it to more amps and less eu/tick would make literately no difference on how much eu the machine consumes, amps in recipes basically just make it possible to cost more eu in the recipe tier without going up into the next tier.
