### ISSUE TITLE
The red alloy cable and the superconductor cable do not have zero resistance.

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#193]
### Describe the feature

If it is a feature, can you add a zero resistance configuration for the Red alloy cable and the Superconductor cable?

if it is a bug, i will go to the Bug Report and re-issue.

——By Bing Translator

### Reasons why it should be considered

In other GT versions I have used, the Red alloy cable and the Superconductor cable have zero resistance.

——By Bing Translator

### Please Read and Confirm the Following

- [X] I have confirmed this feature request is unique and has not been suggested already.

**Comment by Trinsdar** [comment]
It's intentional and I'm not having a config for it, they have partial loss, which means it will round to the nearest int. Imo no cables should have completely 0 loss, ic2 didn't have it that way, so neither should gregtech.
