### ISSUE TITLE
[Bug] Game crash on load

### ISSUE THREAD

**Issue by Xebakyr** [GregTech-Intergalactical/GregTech#195]
### What happened?

Game crashes on load due to 'bad type on Operand stack' error

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
https://gist.github.com/Xebakyr/2decbef045dacc8ee4997ce8af33a2b7
```

### Anything else?

Originally assumed this was some conflict in the mess of a pack i'm building, but adding GTI and all requirements (TesseractAPI and AntimatterAPI) to the pack crashed it, so I cut it down to only GTI and requirements and the issue persists. 

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed GregTech, Antimatter, and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
Your using an old version of gti, you need to get it from the new curseforge page
https://legacy.curseforge.com/minecraft/mc-mods/gti

**Comment by Xebakyr** [comment]
Whoops, didn't find that originally, my bad. Tyvm.
