### ISSUE TITLE
would you please consider making this mod compatible with Immersive Engineering?

### ISSUE THREAD

**Issue by wglpython** [GregTech-Intergalactical/GregTech#196]
### Describe the feature

just compatible Source of energy

### Reasons why it should be considered

you know,they are compatible on both GT5 and GT6

### Please Read and Confirm the Following

- [X] I have confirmed this feature request is unique and has not been suggested already.

**Comment by Trinsdar** [comment]
What exactly do you mean? TesseractAPI already has fe compat, though fe to eu is disabled by default cause fe is unbalanced as fuck

**Comment by wglpython** [comment]
> 你到底是什么意思？TesseractAPI 已经有 fe compat，尽管 fe 到 eu 默认被禁用，因为 fe 和他妈的不平衡

ok,thats my bad

**Comment by wglpython** [comment]
> 你到底是什么意思？TesseractAPI 已经有 fe compat，尽管 fe 到 eu 默认被禁用，因为 fe 和他妈的不平衡
