### ISSUE TITLE
[Bug] The number of items in a single slot of a recipe has overflowed to the maximum, making it impossible to use this recipe.

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/GregTech#201]
### What happened?

Electrolysis of the Bentonite Dust:
![image](https://github.com/GregTech-Intergalactical/GregTech/assets/49526021/168a50b1-4871-4755-a865-a6341f995812)
I've tried using the 64+2 recipe placement method, but the recipe doesn't work.

Other recipes that call for liquids have the same problem. If you use the 4000 L + 4000 L recipe placement method, it cannot be performed by recipes that require 8000 liters.
——Translate by Binag Translator.

### What mod loaders are you seeing the problem on?

Fabric, Forge

### Relevant log output

```shell
N/A
```

### Anything else?

In my time playing this mod, I've only found a few recipe bugs so far, and I'm not sure if there are any other similar cases.
——Translate by Binag Translator.

Best regards

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed GregTech, Antimatter, and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
fixed in dev
