### ISSUE TITLE
[Recipes]

### ISSUE THREAD

**Issue by Raccoon2709** [GregTech-Intergalactical/GregTech#86]
Overall

- Haven't had issues with performance on max settings at 16 chunks and 6GB allocated (nothing build)
- more feedback to come.

In my opinion, things to change

- Remove Vanilla Tools and add Flint Tools
- Magnetite Ore should be a source of Iron (currently not smeltable, both gravel & stone) If this is intended ignore smelting list.
- Small Surface Ores are to common, but i like it very much. (Are they an indicator to underground ores?)
- ~~Gravel Ores are not affected by Gravity.~~
- ~~All Ore (both versions) is smeltable (only) in Vanilla Blast Furnace~~

Following Items have no recipe

- Small {Type} (Stone/Gravel) {Ore} (Iron). Don't have any recipe
- Most machines. I can make a list if needed
- Many Ingot's. If need as above. 

Following Items have no smelting recipe

- {Quantity} (Poor/normal) {Type} (Stone/Gravel) means both versions
[Basic Smelting]
(Iron Ingot)
-Banded Iron
-Brown Limonite
-Yellow Limonite
-Pyrite
-Magnetite
-Iron
-{Type} Iron Dust
(Copper)
-Malachite
-Copper
-Chalcocite
-Chalcopyrite
-Tetrahedrite

**Comment by Gurkysword12** [comment]
Could u make a list of the ingot recipes that need to get added + machines would be very helpful

**Comment by Gurkysword12** [comment]
I will add all these things so be sure to type everything u have found

**Comment by Raccoon2709** [comment]
Hey, you've seen thats from 2021? Not sure if these issues still exist.

**Comment by Gurkysword12** [comment]
They might u can never be too sure

**Comment by Trinsdar** [comment]
@Raccoon2709 I suspect a lot of the missing recipes are still missing, this mod has not gotten much attention at all. If you could, would you edit this issue to reflect the current state of the mod in dev? github actions should have jars you can download.

**Comment by Raccoon2709** [comment]
Earliest I could deliver is January, currently working 14/7 a week till December.
