### ISSUE TITLE
Broken villages?

### ISSUE THREAD

**Issue by Ludi87** [GregTech-Intergalactical/GregTech#87]
Forge 36.0.42
AntimatterAPI 0.1
GTI 0.1
TesseractAPI 0.1
JEI-1.16.5-7.6.1.75

Teleported to Village, theres no houses, only a couple of hybales, paths and rubber trees. No idea if something broke the generation

[Latest.log](https://pastebin.com/1Btg30qb)

![2021-03-25_09 34 07](https://user-images.githubusercontent.com/13112051/112443871-b98dac80-8d4d-11eb-9ed2-969387b20c09.png)

**Comment by Trinsdar** [comment]
closing cause I'm guessing this is no longer an issue, let me know if it is still
