### ISSUE TITLE
[Suggestion] About drops from ores

### ISSUE THREAD

**Issue by Exzept1on** [GregTech-Intergalactical/GregTech#89]
The idea is that a pile of different ores does not clog the inventory, you can make that when digging up the ore, one ore would fall out, for example, stone. After all, in the pulverizer, we can still get only stone dust with a chance.

**Comment by Vliro** [comment]
I do not exactly understand what you mean.

**Comment by repo-alt** [comment]
Probably meant granite/endstone/netherrack ore version. Also, they should give proper stone dust version in the pulverizer, so, idk

**Comment by Exzept1on** [comment]
Sorry, I just use a translator, and it translates poorly. What I wanted to say again. The GTI has different versions of the ore in granite/stone/diorite/andesite. And if all this is extracted, it clutters up the inventory. I propose to make the stone version fall from any version of the ore, because in the crusher, stone dust is obtained from any version in by-product.

**Comment by Vliro** [comment]
They will have different dusts.

**Comment by Exzept1on** [comment]
Perhaps, then, to make a backpack, in which, for example, in the size of 128 pieces, ore will be added when it gets into the inventory.

**Comment by Vliro** [comment]
Honestly I don't feel that GT should add its own backpacks, there are many mods that have those.
