### ISSUE TITLE
Cell chem

### ISSUE THREAD

**Issue by htmlcsjs** [GregTech-Intergalactical/GregTech#91]
any chance of chemistry from GTCE, as in no cell chem

**Comment by Vliro** [comment]
You mean multiple outputs etc instead of cells? Not sure. @GregTech-Intergalactical/collaborator .

**Comment by repo-alt** [comment]
Isn't LCR ported from GT5 ?

**Comment by htmlcsjs** [comment]
both inputs and outputs. alot of people i see hate chell chem

**Comment by Trinsdar** [comment]
In gt4r i did multiple fluid outputs and inputs,  so i don't think it's a bad idea,  but it's up to you whether you want to do cells like gt5 or fluids like gt6.

**Comment by Vliro** [comment]
Not sure. Not the greatest fan of cells either but multiple fluid outputs has its own oddities.

**Comment by Trinsdar** [comment]
This is how i did the centrifuge and electrolyzer,  those 2 are the most odd out of them all: https://github.com/Trinsdar/GT-4-Reimagined/blob/dev-1.16/src/main/resources/assets/gt4r/textures/gui/machine/centrifuge.png

**Comment by Vliro** [comment]
@Trinsdar tbh that looks funky, does it work properly with outputs though? Havent tested. But probably use some switchable panel, a bit like GTCE.

**Comment by Trinsdar** [comment]
Yiu mean buttons or recipes or what exactly? I think it does work l,  though the buttons get in the way

**Comment by Vliro** [comment]
I mean, either way works as both are supported, for now up to recipe creators. But will probably add support for switchable GUI if a machine has more than 1 fluid output/input. However, it should be balanced as the LCR should other this functionality

**Comment by Rongmario** [comment]
Yeah @Vliro is right, multi fluid output mechanic is supported and we'll try and go towards no-cell chem recipes, cells are preferably left for other purposes

**Comment by Vliro** [comment]
@Trinsdar meant if it actually properly outputted multiple fluids.

**Comment by Rongmario** [comment]
None of the covers supports that atm but with other mods, it may be possible iirc

**Comment by Trinsdar** [comment]
Not sure,  i think it mught now though for sure since [#122](https://github.com/GregTech-Intergalactical/AntimatterAPI/pull/122) in antimatter was merged
I'll test it and let you know.

**Comment by Vliro** [comment]
cell chem won't be present.
