### ISSUE TITLE
Request for cool addition at some point

### ISSUE THREAD

**Issue by KubiRemPL** [GregTech-Intergalactical/GregTech#92]
CraftTweaker or KubeJS ability to create custom multiblocks would be very cool for modpack makers
Something like MultiblockTweaker by Eutropium did but sadly only for 1.12.2
I know there is a lot more stuff to do right  now with GTI....

Best Regards
Kubi

**Comment by Vliro** [comment]
Not sure, would feel limited to do it outside of a separate mod.

**Comment by Rongmario** [comment]
I suppose it is possible...

**Comment by Freebi85** [comment]
Kubejs is automatically available out of the box without further integrations as long as all gregtech recipes uses datapacks.

**Comment by Vliro** [comment]
Oh really? GT isn't using datapacks yet but hopefully soon ™

**Comment by Freebi85** [comment]
Glad to hear :) 
At least in order to alter all the recipes in existing GT machines. For custom multiblocks an additional mod is probably required^^

**Comment by Rongmario** [comment]
You can serialize BlockStates pretty easily now, it may be possible to denote a multiblock via json.

**Comment by KubiRemPL** [comment]
Making custom multiblocks via JSON or something is the thing 1.16 modpack makers need.

**Comment by Vliro** [comment]
Well multiblocks is a bit tougher but should be doable, considering that they also need tiles etc.

**Comment by KubiRemPL** [comment]
> Well multiblocks is a bit tougher but should be doable, considering that they also need tiles etc.

Cool then. I am looking forward to see custom multiblocks in my modpack!

**Comment by Vliro** [comment]
Low prio for now. Honestly better to make a mod addition instead for these things.
