### ISSUE TITLE
Copper Wire Connection Crash

### ISSUE THREAD

**Issue by JohnDorianSmith** [GregTech-Intergalactical/GregTech#93]
Greetings,
I just installed this mod today and was messing around in a creative world. I went to connect 2 copper wires together, and then my game crashed.

Here's the crash report:
[crash-2021-03-30_18.17.41-server.txt](https://github.com/GregTech-Intergalactical/GregTech/files/6232521/crash-2021-03-30_18.17.41-server.txt)

Also apologies if I'm not submitting an issue correctly, I'm not an experienced github-er

**Comment by Trinsdar** [comment]
crash report in a paste site for anyone who doesn't want to download the text file: https://gist.github.com/Trinsdar/f08d4b5fe305b8f74094c319354723cb

**Comment by Vliro** [comment]
Strange. Forge 36.1.0+? Missing setutils, weird. Java 8?

**Comment by Vliro** [comment]
Also TesseractAPI?

**Comment by PORTB** [comment]
Also experienced this issue with cobalt wires. Forge 36.1.4, antimatter api 0.0.2, architectury 1.12.145, gt-i 0.0.2, teseract api 0.0.2, java 1.8.0_218
https://pastebin.com/Cfy6zi13

**Comment by PORTB** [comment]
Causing an update to the cable block also has the same effect

**Comment by Vliro** [comment]
This is not a code issue per say but a missing library. Tesseract was installed and forge 36.1.0+?

Ah saw now. Strange. Havent had this. Should soon be a new version available that might fix it either way

**Comment by Vliro** [comment]
This is an issue due to Gradle, shadowing isn't working so it isn't including necessary classes. Will be fixed.

**Comment by Vliro** [comment]
Has been fixed and next jar shall not have this issue
