### ISSUE TITLE
Too many hardcoded texts

### ISSUE THREAD

**Issue by ChromaPIE** [GregTech-Intergalactical/GregTech#94]
Many displayed texts seem to be hardcoded, not so sure because I didn't see them anywhere in the json file under lang folder.

Those texts including the stat titles like Duration, Amps, Total etc. in JEI, `Hold Shift to show formula` in tooltips, `Idle` in machine GUIs, and more.These are making gameplay experience in localized environment pretty weird and disharmonious. Hoping to see them fixed in the feature.

**Comment by Vliro** [comment]
There is only english language available, and texts are generated dynamically so they aren't the best. For now, only English will be available.

**Comment by ChromaPIE** [comment]
Sorry if I didn't make the issue clear enough. I'm not a native English speaker therefore in order to get rid of the problem making me have to translate texts in my brain I would like to translate mods in my private instance being enjoyed, with the help of OpenLoader and that's why I noticed that some of the texts in GTI don't have corresponding localization keys present in the JSON language file, which is causing a kind of uncomfortable feeling for me which GTCE won't as all of the texts it shown are able to be localized. It should be all or nothing, but playing with a mod in which 80% are localized but the rest are laid where you can't reach, that's not nice.

However it's understandable as GTI is in early alpha. Hopefully it could be inplemented. It deserves a wait.

**Comment by Vliro** [comment]
Right now literally all language is generated programatically, not via JSON. However, it does support multiple languages, but json is automatically built.

**Comment by Trinsdar** [comment]
Yah tooltips and such though aren't able to be automatically generated like other things are, so therefore lang is not a priority for them.  I'm sure this will be dealt with eventually, just not now

**Comment by Rongmario** [comment]
> However it's understandable as GTI is in early alpha. Hopefully it could be inplemented. It deserves a wait.

That's why they're literally just printlns and TextComponents; they were for debug and no pretty printing or whatever. They'll become translation strings of course.

**Comment by ChromaPIE** [comment]
It's a bit confusing to me that en_us is nowhere to be found currenctly but there do have an en_us locale in game, sorry for I know nothing about how things work but where are the locales be defined now?

**Comment by Vliro** [comment]
It's generated via code, the en_US class inside a language provider

**Comment by ChromaPIE** [comment]
I see. So any ways to dump all available translation keys provided by GTI and AntimatterAPI to a JSON? Don't mind me, just asking.
